window.PORTFOLIO_PROJECTS = [
  {
    id: "reportes-urbanos",
    nombre: "Reportes Urbanos",
    slug: "reportes-urbanos",
    descripcionCorta: "Aplicación web de georreferenciación",
    descripcionCompleta: "Desarrollo de una aplicación full stack para registrar y visualizar puntos, rutas y zonas mediante mapas interactivos. Implementación de operaciones CRUD, autenticación con JWT y almacenamiento de información geoespacial en MongoDB Atlas. Documentación de la API con Swagger, integración de frontend y backend, control de versiones con GitHub y despliegue en Vercel.",
    imagenPrincipal: "./img/where.png",
    galeria: ["./img/urban/1.png", "./img/urban/2.png", "./img/urban/3.png", "./img/urban/4.png", "./img/urban/5.png", "./img/urban/6.png"],
    categoria: "Aplicación web",
    tecnologias: ["Angular", "Node.js", "Express", "MongoDB Atlas", "Leaflet", "JWT", "Swagger", "Vercel"],
    caracteristicas: ["CRUD", "Mapas interactivos", "Autenticación JWT", "Documentación Swagger"],
    contribucionPersonal: null,
    aprendizajes: null,
    estado: "Desplegado",
    repositorio: "https://github.com/PeytonDenisse/ReportesUrbanos",
    demostracion: "https://reportes-urbanos-five.vercel.app/",
    documentacion: "https://reportes-urbanos-five.vercel.app/api-docs",
    destacado: true,
    orden: 1
  },
  {
    id: "natureapp",
    nombre: "NatureApp",
    slug: "natureapp",
    descripcionCorta: "Plataforma de exploración de lugares naturales",
    descripcionCompleta: "Desarrollo de una plataforma web para administrar y visualizar lugares naturales. Integración de frontend en Angular con una API REST desarrollada en .NET. Uso de Docker y Docker Compose para la contenerización y configuración de servicios, además de herramientas de nube y control de versiones.",
    imagenPrincipal: "./img/nap.png",
    galeria: ["./img/natureapp/natapp.mp4"],
    categoria: "Aplicación web",
    tecnologias: ["Angular", ".NET", "APIs REST", "Docker", "Docker Compose"],
    caracteristicas: ["Administración de lugares naturales", "API REST", "Contenerización"],
    contribucionPersonal: null,
    aprendizajes: null,
    estado: "En portafolio",
    repositorio: "https://github.com/PeytonDenisse/NatureFRONT_Chagoya",
    demostracion: null,
    documentacion: null,
    destacado: true,
    orden: 2
  },
  {
    id: "vetcare",
    nombre: "VetCare",
    slug: "vetcare",
    descripcionCorta: "Sistema de gestión veterinaria",
    descripcionCompleta: "Desarrollo de un sistema web para la gestión de usuarios y servicios veterinarios. Implementación de autenticación con Google mediante Firebase Authentication. Integración del frontend en Angular con una API REST desarrollada en Java y persistencia de información en MySQL.",
    imagenPrincipal: "./img/vetcare.png",
    galeria: ["./img/vetcare/vet.mp4"],
    categoria: "Aplicación web",
    tecnologias: ["Angular", "Java", "MySQL", "Firebase"],
    caracteristicas: ["Gestión de usuarios", "Servicios veterinarios", "Autenticación con Google"],
    contribucionPersonal: null,
    aprendizajes: null,
    estado: "En portafolio",
    repositorio: "https://github.com/PeytonDenisse/VetCAre_app",
    demostracion: null,
    documentacion: null,
    destacado: true,
    orden: 3
  },
  {
    id: "catalogo-moda",
    nombre: "Catálogo Moda (Django)",
    slug: "catalogo-moda-django",
    descripcionCorta: "Gestión de productos y pedidos",
    descripcionCompleta: "Aplicación web para la gestión de productos, categorías y pedidos. Incluye autenticación de usuarios y panel de administración.",
    imagenPrincipal: "./img/djangoYpython.jpg",
    galeria: ["./img/catalogo/cmvideo.mp4"],
    categoria: "Aplicación web",
    tecnologias: ["Python", "Django", "Bootstrap", "MySQL"],
    caracteristicas: ["Gestión de productos", "Gestión de categorías", "Gestión de pedidos", "Autenticación", "Panel de administración"],
    contribucionPersonal: null,
    aprendizajes: null,
    estado: "En portafolio",
    repositorio: "https://github.com/PeytonDenisse/Catalogo_Moda_APP",
    demostracion: null,
    documentacion: null,
    destacado: false,
    orden: 4
  },
  {
    id: "detector-pastillas",
    nombre: "Detector de Pastillas (OpenCV)",
    slug: "detector-pastillas-opencv",
    descripcionCorta: "Visión por computadora",
    descripcionCompleta: "Sistema de visión por computadora para identificar pastillas y estimar faltantes en un empaque mediante OpenCV.",
    imagenPrincipal: "./img/pythonCV.png",
    galeria: ["./img/pastillas/demo.mp4", "./img/pastillas/1.png", "./img/pastillas/2.png", "./img/pastillas/3.png", "./img/pastillas/4.png", "./img/pastillas/5.png", "./img/pastillas/6.png"],
    categoria: "Visión por computadora",
    tecnologias: ["Python", "OpenCV"],
    caracteristicas: ["Identificación de pastillas", "Estimación de faltantes"],
    contribucionPersonal: null,
    aprendizajes: null,
    estado: "Desplegado",
    repositorio: "https://github.com/PeytonDenisse/Deterctor_Pastillas",
    demostracion: "https://deterctorpastillasdenissechagoya.streamlit.app/",
    documentacion: null,
    destacado: false,
    orden: 5
  },
  {
    id: "recetario-app",
    nombre: "Recetario App (Android)",
    slug: "recetario-app-android",
    descripcionCorta: "Desarrollo móvil nativo",
    descripcionCompleta: "Aplicación móvil para Android con Jetpack Compose para visualizar recetas consumiendo una API REST.",
    imagenPrincipal: "./img/kotlin.png",
    galeria: ["./img/recetario/receta.mp4"],
    categoria: "Desarrollo móvil",
    tecnologias: ["Kotlin", "Android", "Jetpack Compose", "Retrofit"],
    caracteristicas: ["Visualización de recetas", "Consumo de API REST"],
    contribucionPersonal: null,
    aprendizajes: null,
    estado: "En portafolio",
    repositorio: "https://github.com/PeytonDenisse/RecetarioApp",
    demostracion: null,
    documentacion: null,
    destacado: false,
    orden: 6
  }
];
